databases:
  - name: wger-db
    databaseName: wger
    user: wger

services:
  - type: redis
    name: wger-redis
    plan: free
    ipAllowList: []

  - type: web
    name: wger-web
    env: docker
    dockerfilePath: extras/docker/production/Dockerfile
    envVars:
      - key: WGER_USE_GUNICORN
        value: "True"
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_PERFORM_MIGRATIONS
        value: "True"
      - key: SITE_URL
        value: "https://wger-web.onrender.com" # You can update this to your final Render URL later
      - key: SECRET_KEY
        generateValue: true
      - key: SIGNING_KEY
        generateValue: true
      - key: DJANGO_DB_ENGINE
        value: django.db.backends.postgresql
      - key: DJANGO_DB_DATABASE
        fromDatabase:
          name: wger-db
          property: database
      - key: DJANGO_DB_USER
        fromDatabase:
          name: wger-db
          property: user
      - key: DJANGO_DB_PASSWORD
        fromDatabase:
          name: wger-db
          property: password
      - key: DJANGO_DB_HOST
        fromDatabase:
          name: wger-db
          property: host
      - key: DJANGO_DB_PORT
        fromDatabase:
          name: wger-db
          property: port
      - key: CELERY_BROKER
        fromService:
          type: redis
          name: wger-redis
          property: connectionString
      - key: CELERY_BACKEND
        fromService:
          type: redis
          name: wger-redis
          property: connectionString
      - key: DJANGO_CACHE_BACKEND
        value: "django.core.cache.backends.redis.RedisCache"
      - key: DJANGO_CACHE_LOCATION
        fromService:
          type: redis
          name: wger-redis
          property: connectionString
      - key: USE_CELERY
        value: "True"

  - type: worker
    name: wger-worker
    env: docker
    dockerfilePath: extras/docker/production/Dockerfile
    dockerCommand: /start-worker
    envVars:
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_PERFORM_MIGRATIONS
        value: "False"
      - key: DJANGO_DB_ENGINE
        value: django.db.backends.postgresql
      - key: DJANGO_DB_DATABASE
        fromDatabase:
          name: wger-db
          property: database
      - key: DJANGO_DB_USER
        fromDatabase:
          name: wger-db
          property: user
      - key: DJANGO_DB_PASSWORD
        fromDatabase:
          name: wger-db
          property: password
      - key: DJANGO_DB_HOST
        fromDatabase:
          name: wger-db
          property: host
      - key: DJANGO_DB_PORT
        fromDatabase:
          name: wger-db
          property: port
      - key: CELERY_BROKER
        fromService:
          type: redis
          name: wger-redis
          property: connectionString
      - key: CELERY_BACKEND
        fromService:
          type: redis
          name: wger-redis
          property: connectionString
      - key: DJANGO_CACHE_BACKEND
        value: "django.core.cache.backends.redis.RedisCache"
      - key: DJANGO_CACHE_LOCATION
        fromService:
          type: redis
          name: wger-redis
          property: connectionString
      - key: USE_CELERY
        value: "True"
